#!/usr/bin/env python3
"""Generate localization.csv with all UI strings in 18 languages."""
import csv
import os

LANGS = ['en','es','fr','de','pt','it','nl','ru','ja','ko','zh','zh_TW','ar','hi','tr','pl','th','id']

# fmt: off
STRINGS = [
# === COMMON ===
['common_cancel','Cancel','Cancelar','Annuler','Abbrechen','Cancelar','Annulla','Annuleren','Отмена','キャンセル','취소','取消','取消','إلغاء','रद्द','İptal','Anuluj','ยกเลิก','Batal'],
['common_ok','OK','OK','OK','OK','OK','OK','OK','ОК','OK','확인','确定','確定','موافق','ठीक है','Tamam','OK','ตกลง','OK'],
['common_retry','Retry','Reintentar','Réessayer','Wiederholen','Tentar novamente','Riprova','Opnieuw','Повторить','再試行','다시 시도','重试','重試','إعادة المحاولة','पुनः प्रयास','Tekrar dene','Ponów','ลองอีกครั้ง','Coba lagi'],
['common_save','Save','Guardar','Enregistrer','Speichern','Salvar','Salva','Opslaan','Сохранить','保存','저장','保存','儲存','حفظ','सहेजें','Kaydet','Zapisz','บันทึก','Simpan'],
['common_delete','Delete','Eliminar','Supprimer','Löschen','Excluir','Elimina','Verwijderen','Удалить','削除','삭제','删除','刪除','حذف','हटाएं','Sil','Usuń','ลบ','Hapus'],
['common_close','Close','Cerrar','Fermer','Schließen','Fechar','Chiudi','Sluiten','Закрыть','閉じる','닫기','关闭','關閉','إغلاق','बंद करें','Kapat','Zamknij','ปิด','Tutup'],
['common_done','Done','Listo','Terminé','Fertig','Concluído','Fatto','Klaar','Готово','完了','완료','完成','完成','تم','पूर्ण','Bitti','Gotowe','เสร็จสิ้น','Selesai'],
['common_submit','Submit','Enviar','Soumettre','Absenden','Enviar','Invia','Verzenden','Отправить','送信','제출','提交','提交','إرسال','भेजें','Gönder','Wyślij','ส่ง','Kirim'],
['common_search','Search','Buscar','Rechercher','Suchen','Pesquisar','Cerca','Zoeken','Поиск','検索','검색','搜索','搜尋','بحث','खोजें','Ara','Szukaj','ค้นหา','Cari'],
['common_loading','Loading...','Cargando...','Chargement...','Laden...','Carregando...','Caricamento...','Laden...','Загрузка...','読み込み中...','로딩중...','加载中...','載入中...','جار التحميل...','लोड हो रहा...','Yükleniyor...','Ładowanie...','กำลังโหลด...','Memuat...'],
['common_error','Error','Error','Erreur','Fehler','Erro','Errore','Fout','Ошибка','エラー','오류','错误','錯誤','خطأ','त्रुटि','Hata','Błąd','ข้อผิดพลาด','Kesalahan'],
['common_success','Success','\Éxito','Succ\ès','Erfolg','Sucesso','Successo','Succes','Успех','成功','성공','成功','成功','نجاح','सफल','Başarılı','Sukces','สำเร็จ','Berhasil'],
['common_coming_soon','Coming soon','Próximamente','Bientôt','Demnächst','Em breve','Prossimamente','Binnenkort','Скоро','近日公開','곧 출시','即将推出','即將推出','قريباً','जल्द आ रहा है','Yakında','Wkrótce','เร็วๆ นี้','Segera hadir'],
['common_clear','Clear','Limpiar','Effacer','Leeren','Limpar','Cancella','Wissen','Очистить','クリア','지우기','清除','清除','مسح','साफ़ करें','Temizle','Wyczyść','ล้าง','Hapus'],
['common_upgrade','Upgrade','Mejorar plan','Mettre à niveau','Upgraden','Atualizar','Aggiorna','Upgraden','Обновить','アップグレード','업그레이드','升级','升級','ترقية','अपग्रेड','Yükselt','Uaktualnij','อัปเกรด','Tingkatkan'],
['common_confirm','Confirm','Confirmar','Confirmer','Bestätigen','Confirmar','Conferma','Bevestigen','Подтвердить','確認','확인','确认','確認','تأكيد','पुष्टि','Onayla','Potwierdź','ยืนยัน','Konfirmasi'],
['common_apply','Apply','Aplicar','Appliquer','Anwenden','Aplicar','Applica','Toepassen','Применить','適用','적용','应用','套用','تطبيق','लागू करें','Uygula','Zastosuj','ใช้งาน','Terapkan'],
['common_edit','Edit','Editar','Modifier','Bearbeiten','Editar','Modifica','Bewerken','Редактировать','編集','편집','编辑','編輯','تعديل','संपादित','Düzenle','Edytuj','แก้ไข','Edit'],
['common_create','Create','Crear','Créer','Erstellen','Criar','Crea','Maken','Создать','作成','만들기','创建','建立','إنشاء','बनाएं','Oluştur','Utwórz','สร้าง','Buat'],
['common_share','Share','Compartir','Partager','Teilen','Compartilhar','Condividi','Delen','Поделиться','共有','공유','分享','分享','مشارкة','साझा करें','Paylaş','Udostępnij','แชร์','Bagikan'],
['common_copy','Copy','Copiar','Copier','Kopieren','Copiar','Copia','Kopiëren','Копировать','コピー','복사','复制','複製','نسخ','कॉपी','Kopyala','Kopiuj','คัดลอก','Salin'],
['common_copied','Copied to clipboard','Copiado','Copié','Kopiert','Copiado','Copiato','Gekopieerd','Скопировано','コピーしました','복사됨','已复制','已複製','تم النسخ','कॉपी हो गया','Kopyalandı','Skopiowano','คัดลอกแล้ว','Disalin'],
['common_sign_in','Sign In','Iniciar sesión','Se connecter','Anmelden','Entrar','Accedi','Inloggen','Войти','サインイン','로그인','登录','登入','تسجيل الدخول','साइन इन','Giriş yap','Zaloguj się','เข้าสู่ระบบ','Masuk'],
['common_sign_out','Log Out','Cerrar sesión','Se déconnecter','Abmelden','Sair','Esci','Uitloggen','Выйти','ログアウト','로그아웃','退出登录','登出','تسجيل الخروج','लॉग आउट','Çıkış yap','Wyloguj się','ออกจากระบบ','Keluar'],
['common_all','All','Todos','Tous','Alle','Todos','Tutti','Alle','Все','すべて','전체','全部','全部','الكل','सभी','Tümü','Wszystkie','ทั้งหมด','Semua'],
['common_free','Free','Gratis','Gratuit','Kostenlos','Grátis','Gratuito','Gratis','Бесплатно','無料','무료','免费','免費','مجاني','मुफ़्त','Ücretsiz','Bezpłatnie','ฟรี','Gratis'],
['common_settings','Settings','Configuración','Paramètres','Einstellungen','Configurações','Impostazioni','Instellingen','Настройки','設定','설정','设置','設定','الإعدادات','सेटिंग्स','Ayarlar','Ustawienia','ตั้งค่า','Pengaturan'],
['common_profile','Profile','Perfil','Profil','Profil','Perfil','Profilo','Profiel','Профиль','プロフィール','프로필','个人资料','個人資料','الملف الشخصي','प्रोफ़ाइल','Profil','Profil','โปรไฟล์','Profil'],
['common_wallet','Wallet','Billetera','Portefeuille','Wallet','Carteira','Portafoglio','Portemonnee','Кошелек','ウォレット','지갑','钱包','錢包','المحفظة','वॉलेट','Cüzdan','Portfel','กระเป๋าเงิน','Dompet'],
['common_tickets','Tickets','Entradas','Billets','Tickets','Ingressos','Biglietti','Tickets','Билеты','チケット','티켓','门票','票券','تذاкر','टिकट','Biletler','Bilety','ตั๋ว','Tiket'],
['common_events','Events','Eventos','Événements','Events','Eventos','Eventi','Evenementen','События','イベント','이벤트','活动','活動','الفعاليات','इवेंट्स','Etkinlikler','Wydarzenia','อีเวนท์','Acara'],
['common_notifications','Notifications','Notificaciones','Notifications','Benachrichtigungen','Notificações','Notifiche','Meldingen','Уведомления','通知','알림','通知','通知','الإشعارات','सूचनाएं','Bildirimler','Powiadomienia','การแจ้งเตือน','Notifikasi'],
['common_payments','Payments','Pagos','Paiements','Zahlungen','Pagamentos','Pagamenti','Betalingen','Платежи','支払い','결제','支付','付款','المدفوعات','भुगतान','Ödemeler','Płatności','การชำระเงิน','Pembayaran'],
# === AUTH ===
['auth_login_title','Log In','Iniciar sesión','Connexion','Anmelden','Entrar','Accedi','Inloggen','Вход','ログイン','로그인','登录','登入','تسجيل الدخول','लॉग इन','Giriş','Logowanie','เข้าสู่ระบบ','Masuk'],
['auth_login_welcome','Welcome back','Bienvenido de nuevo','Bon retour','Willkommen zurück','Bem-vindo de volta','Bentornato','Welkom terug','С возвращением','おかえりなさい','다시 오신 것을 환영합니다','欢迎回来','歡迎回來','أهلاً بعودتк','वापसी पर स्वागत','Tekrar hoş geldiniz','Witamy ponownie','ยินดีต้อนรับกลับ','Selamat datang kembali'],
['auth_login_subtitle','Sign in to access your tickets','Inicia sesión para acceder a tus entradas','Connectez-vous pour accéder à vos billets','Melden Sie sich an um auf Ihre Tickets zuzugreifen','Entre para acessar seus ingressos','Accedi per visualizzare i tuoi biglietti','Log in om je tickets te bekijken','Войдите для доступа к билетам','チケットにアクセスするにはサインイン','티켓에 접근하려면 로그인하세요','登录以查看您的门票','登入以查看您的票券','سجل الدخول للوصول إلى تذاكرк','अपने टिकट एक्सेस करने के लिए साइन इन करें','Biletlerinize erişmek için giriş yapın','Zaloguj się aby uzyskać dostęp do biletów','เข้าสู่ระบบเพื่อเข้าถึงตั๋วของคุณ','Masuk untuk mengakses tiket Anda'],
['auth_login_email_label','Email','Correo electrónico','E-mail','E-Mail','E-mail','E-mail','E-mail','Эл. почта','メール','이메일','电子邮件','電子郵件','البريد الإلكتروني','ईमेल','E-posta','E-mail','อีเมล','Email'],
['auth_login_password_label','Password','Contraseña','Mot de passe','Passwort','Senha','Password','Wachtwoord','Пароль','パスワード','비밀번호','密码','密碼','كلمة المرور','पासवर्ड','Şifre','Hasło','รหัสผ่าน','Kata sandi'],
['auth_login_forgot','Forgot password?','¿Olvidaste tu contraseña?','Mot de passe oublié?','Passwort vergessen?','Esqueceu a senha?','Password dimenticata?','Wachtwoord vergeten?','Забыли пароль?','パスワードをお忘れですか？','비밀번호를 잊으셨나요?','忘记密码？','忘記密碼？','هل نسيت كلمة المرور؟','पासवर्ड भूल गए?','Şifrenizi mi unuttunuz?','Zapomniałeś hasła?','ลืมรหัสผ่าน?','Lupa kata sandi?'],
['auth_login_no_account','Don\'t have an account?','¿No tienes una cuenta?','Vous n\'avez pas de compte?','Kein Konto?','Não tem uma conta?','Non hai un account?','Geen account?','Нет аккаунта?','アカウントをお持ちでないですか？','계정이 없으신가요?','还没有账号？','還沒有帳號？','ليس لديк حساب؟','अकाउंट नहीं है?','Hesabınız yok mu?','Nie masz konta?','ยังไม่มีบัญชี?','Belum punya akun?'],
['auth_login_signup_link','Sign up','Regístrate','S\'inscrire','Registrieren','Cadastrar','Registrati','Registreren','Зарегистрироваться','登録','회원가입','注册','註冊','إنشاء حساب','साइन अप','Kaydol','Zarejestruj się','สมัครสมาชิก','Daftar'],
['auth_login_reset_sent','Password reset email sent','Correo de restablecimiento enviado','E-mail de réinitialisation envoyé','Passwort-Reset-E-Mail gesendet','E-mail de redefinição enviado','E-mail di reset inviata','Reset e-mail verzonden','Письмо для сброса пароля отправлено','パスワードリセットメールを送信しました','비밀번호 재설정 이메일이 전송되었습니다','密码重置邮件已发送','密碼重置郵件已發送','تم إرسال بريد إعادة تعيين كلمة المرور','पासवर्ड रीसेट ईमेल भेजा गया','Şifre sıfırlama e-postası gönderildi','Wysłano e-mail z resetem hasła','ส่งอีเมลรีเซ็ตรหัสผ่านแล้ว','Email reset kata sandi telah dikirim'],
['auth_signup_title','Sign Up','Registrarse','S\'inscrire','Registrieren','Cadastrar','Registrati','Registreren','Регистрация','登録','회원가입','注册','註冊','إنشاء حساب','साइन अप','Kaydol','Rejestracja','สมัครสมาชิก','Daftar'],
['auth_signup_welcome','Create account','Crear cuenta','Créer un compte','Konto erstellen','Criar conta','Crea account','Account aanmaken','Создать аккаунт','アカウントを作成','계정 만들기','创建账号','建立帳號','إنشاء حساب','अकाउंट बनाएं','Hesap oluştur','Utwórz konto','สร้างบัญชี','Buat akun'],
['auth_signup_subtitle','Start discovering amazing events','Comienza a descubrir eventos increíbles','Découvrez des événements incroyables','Entdecke tolle Events','Comece a descobrir eventos incríveis','Inizia a scoprire eventi fantastici','Ontdek geweldige evenementen','Откройте для себя удивительные события','素晴らしいイベントを見つけよう','놀라운 이벤트를 발견하세요','开始发现精彩活动','開始發現精彩活動','ابدأ باكتشاف الأحداث المذهلة','अद्भुत इवेंट्स खोजना शुरू करें','Harika etkinlikleri keşfetmeye başlayın','Zacznij odkrywać niesamowite wydarzenia','เริ่มค้นพบอีเวนท์ที่น่าทึ่ง','Mulai temukan acara luar biasa'],
['auth_signup_username','Username','Nombre de usuario','Nom d\'utilisateur','Benutzername','Nome de usuário','Nome utente','Gebruikersnaam','Имя пользователя','ユーザー名','사용자 이름','用户名','使用者名稱','اسم المستخدم','यूज़रनेम','Kullanıcı adı','Nazwa użytkownika','ชื่อผู้ใช้','Nama pengguna'],
['auth_signup_confirm_password','Confirm password','Confirmar contraseña','Confirmer le mot de passe','Passwort bestätigen','Confirmar senha','Conferma password','Bevestig wachtwoord','Подтвердите пароль','パスワード確認','비밀번호 확인','确认密码','確認密碼','تأكيد كلمة المرور','पासवर्ड की पुष्टि','Şifreyi onayla','Potwierdź hasło','ยืนยันรหัสผ่าน','Konfirmasi kata sandi'],
['auth_signup_referral','Referral code (optional)','Código de referido (opcional)','Code de parrainage (optionnel)','Empfehlungscode (optional)','Código de indicação (opcional)','Codice referral (opzionale)','Verwijzingscode (optioneel)','Реферальный код (необязательно)','紹介コード（任意）','추천 코드 (선택 사항)','推荐码（可选）','推薦碼（可選）','رمز الإحالة (اختياري)','रेफ़रल कोड (वैकल्पिक)','Referans kodu (opsiyonel)','Kod polecenia (opcjonalnie)','รหัสผู้แนะนำ (ไม่บังคับ)','Kode referral (opsional)'],
['auth_signup_button','Create Account','Crear cuenta','Créer un compte','Konto erstellen','Criar conta','Crea account','Account aanmaken','Создать аккаунт','アカウント作成','계정 만들기','创建账号','建立帳號','إنشاء حساب','अकाउंट बनाएं','Hesap oluştur','Utwórz konto','สร้างบัญชี','Buat akun'],
['auth_signup_have_account','Already have an account?','¿Ya tienes una cuenta?','Vous avez déjà un compte?','Bereits ein Konto?','Já tem uma conta?','Hai già un account?','Heb je al een account?','Уже есть аккаунт?','すでにアカウントをお持ちですか？','이미 계정이 있으신가요?','已有账号？','已有帳號？','لديк حساب بالفعل؟','पहले से अकाउंट है?','Zaten hesabınız var mı?','Masz już konto?','มีบัญชีอยู่แล้ว?','Sudah punya akun?'],
['auth_signup_passwords_mismatch','Passwords do not match','Las contraseñas no coinciden','Les mots de passe ne correspondent pas','Passwörter stimmen nicht überein','As senhas não coincidem','Le password non corrispondono','Wachtwoorden komen niet overeen','Пароли не совпадают','パスワードが一致しません','비밀번호가 일치하지 않습니다','密码不匹配','密碼不匹配','كلمات المرور غير متطابقة','पासवर्ड मेल नहीं खाते','Şifreler eşleşmiyor','Hasła nie są identyczne','รหัสผ่านไม่ตรงกัน','Kata sandi tidak cocok'],
['auth_signup_success','Account created successfully!','¡Cuenta creada exitosamente!','Compte créé avec succès!','Konto erfolgreich erstellt!','Conta criada com sucesso!','Account creato con successo!','Account succesvol aangemaakt!','Аккаунт успешно создан!','アカウントが正常に作成されました！','계정이 성공적으로 생성되었습니다!','账号创建成功！','帳號建立成功！','تم إنشاء الحساب بنجاح!','अकाउंट सफलतापूर्वक बनाया गया!','Hesap başarıyla oluşturuldu!','Konto utworzone pomyślnie!','สร้างบัญชีสำเร็จ!','Akun berhasil dibuat!'],
# === SETTINGS ===
['settings_title','Settings','Configuración','Paramètres','Einstellungen','Configurações','Impostazioni','Instellingen','Настройки','設定','설정','设置','設定','الإعدادات','सेटिंग्स','Ayarlar','Ustawienia','ตั้งค่า','Pengaturan'],
['settings_appearance','Appearance','Apariencia','Apparence','Darstellung','Aparência','Aspetto','Uiterlijk','Внешний вид','外観','외관','外观','外觀','المظهر','दिखावट','Görünüm','Wygląd','รูปลักษณ์','Tampilan'],
['settings_dark_mode','Dark Mode','Modo oscuro','Mode sombre','Dunkelmodus','Modo escuro','Modalità scura','Donkere modus','Темная тема','ダークモード','다크 모드','深色模式','深色模式','الوضع المظلم','डार्क मोड','Karanlık mod','Tryb ciemny','โหมดมืด','Mode gelap'],
['settings_light_mode','Light Mode','Modo claro','Mode clair','Hellmodus','Modo claro','Modalità chiara','Lichte modus','Светлая тема','ライトモード','라이트 모드','浅色模式','淺色模式','الوضع الفاتح','लाइट मोड','Aydınlık mod','Tryb jasny','โหมดสว่าง','Mode terang'],
['settings_toggle_hint','Tap the icon to toggle','Toca el icono para cambiar','Appuyez pour changer','Tippen Sie zum Umschalten','Toque o ícone para alternar','Tocca l\'icona per cambiare','Tik op het pictogram','Tap to change','アイコンをタップして切り替え','ايكون على الضغط','Tik','Артулуй','Simgeye dokun','แตะไอคอนเพื่อสลับ','Ketuk ikon','आइकॉन टैप करें','Kliknięcie ikony','แตะไอคอนเพื่อสลับ','Ketuk ikon untuk mengubah'],
['settings_system','System','Sistema','Système','System','Sistema','Sistema','Systeem','Система','システム','시스템','系统','系統','النظام','सिस्टम','Sistem','Systemowy','ระบบ','Sistem'],
['settings_light','Light','Claro','Clair','Hell','Claro','Chiaro','Licht','Светлая','ライト','라이트','浅色','淺色','فاتح','लाइट','Aydınlık','Jasny','สว่าง','Terang'],
['settings_dark','Dark','Oscuro','Sombre','Dunkel','Escuro','Scuro','Donker','Темная','ダーク','다크','深色','深色','مظلم','डार्क','Karanlık','Ciemny','มืด','Gelap'],
['settings_notifications','Notifications','Notificaciones','Notifications','Benachrichtigungen','Notificações','Notifiche','Meldingen','Уведомления','通知','알림','通知','通知','الإشعارات','सूचनाएं','Bildirimler','Powiadomienia','การแจ้งเตือน','Notifikasi'],
['settings_notification_prefs','Notification Preferences','Preferencias de notificaciones','Préférences de notifications','Benachrichtigungseinstellungen','Preferências de notificação','Preferenze notifiche','Notificatie-instellingen','Настройки уведомлений','通知設定','알림 설정','通知设置','通知設定','تفضيلات الإشعارات','सूचना प्राथमिकताएं','Bildirim tercihleri','Preferencje powiadomień','ตั้งค่าการแจ้งเตือน','Preferensi notifikasi'],
['settings_notification_prefs_sub','Manage push email and alert settings','Administrar push correo y alertas','Gérer push e-mail et alertes','Push E-Mail und Warnungen verwalten','Gerenciar push e-mail e alertas','Gestisci push e-mail e avvisi','Beheer push e-mail en meldingen','Управление пуш почтой и оповещениями','プッシュ・メール・アラート設定を管理','푸시 이메일 알림 관리','管理推送邮件和提醒设置','管理推送郵件和提醒設定','إدارة الإشعارات والتنبيهات','पुश ईमेल और अलर्ट सेटिंग प्रबंधित करें','Push e-posta ve uyarı ayarlarını yönet','Zarządzaj ustawieniami powiadomień','จัดการการแจ้งเตือนและการแจ้ง','Kelola pengaturan push email dan peringatan'],
['settings_general','General','General','Général','Allgemein','Geral','Generale','Algemeen','Общие','一般','일반','常规','一般','عام','सामान्य','Genel','Ogólne','ทั่วไป','Umum'],
['settings_language','Language','Idioma','Langue','Sprache','Idioma','Lingua','Taal','Язык','言語','언어','语言','語言','اللغة','भाषा','Dil','Język','ภาษา','Bahasa'],
['settings_location','Location','Ubicación','Localisation','Standort','Localização','Posizione','Locatie','Местоположение','位置情報','위치','位置','位置','الموقع','स्थान','Konum','Lokalizacja','ตำแหน่ง','Lokasi'],
['settings_location_subtitle','Allow location access for nearby events','Permitir acceso a ubicación para eventos cercanos','Autoriser l\'accès à la localisation','Standortzugriff für nahe Events erlauben','Permitir acesso à localização','Consenti accesso posizione per eventi vicini','Locatietoegang toestaan','Location access','近くのイベントのために位置情報を許可','السماح بالوصول','Toestaan','Разрешить','Yakındaki etkinlikler için konum erişimi','อนุญาตการเข้าถึงตำแหน่ง','Izinkan akses lokasi','नजदीकी इवेंट्स के लिए स्थान अनुमति दें','Zezwól na dostęp do lokalizacji','อนุญาตการเข้าถึงตำแหน่งสำหรับอีเวนท์ใกล้เคียง','Izinkan akses lokasi untuk acara terdekat'],
['settings_currency','Currency','Moneda','Devise','Währung','Moeda','Valuta','Valuta','Валюта','通貨','통화','货币','貨幣','العملة','मुद्रा','Para birimi','Waluta','สกุลเงิน','Mata uang'],
['settings_currency_wallet_msg','Currency can be changed from the Wallet screen','La moneda se puede cambiar desde la Billetera','La devise peut être changée depuis le Portefeuille','Währung kann im Wallet geändert werden','A moeda pode ser alterada na Carteira','La valuta può essere cambiata dal Portafoglio','Valuta kan worden gewijzigd in Portemonnee','Валюту можно изменить в кошельке','ウォレットから変更できます','지갑 화면에서 변경 가능','可在钱包页面更改','可在錢包頁面變更','يمكن تغيير العملة من المحفظة','वॉलेट स्क्रीन से मुद्रा बदली जा सकती है','Para birimi Cüzdan ekranından değiştirilebilir','Walutę można zmienić w Portfelu','สกุลเงินสามารถเปลี่ยนได้จากหน้ากระเป๋าเงิน','Mata uang dapat diubah dari layar Dompet'],
['settings_about','About','Acerca de','À propos','Über','Sobre','Informazioni','Over','О приложении','アプリについて','앱 정보','关于','關於','حول','के बारे में','Hakkında','O aplikacji','เกี่ยวกับ','Tentang'],
['settings_version','Version','Versión','Version','Version','Versão','Versione','Versie','Версия','バージョン','버전','版本','版本','الإصدار','संस्करण','Sürüm','Wersja','เวอร์ชัน','Versi'],
['settings_terms','Terms of Service','Términos de servicio','Conditions d\'utilisation','Nutzungsbedingungen','Termos de serviço','Termini di servizio','Servicevoorwaarden','Условия использования','利用規約','이용 약관','服务条款','服務條款','شروط الخدمة','सेवा की शर्तें','Kullanım koşulları','Regulamin','ข้อกำหนดการใช้งาน','Ketentuan layanan'],
['settings_privacy','Privacy Policy','Política de privacidad','Politique de confidentialité','Datenschutzrichtlinie','Política de privacidade','Informativa sulla privacy','Privacybeleid','Политика конфиденциальности','プライバシーポリシー','개인정보 처리방침','隐私政策','隱私政策','سياسة الخصوصية','गोपनीयता नीति','Gizlilik politikası','Polityka prywatności','นโยบายความเป็นส่วนตัว','Kebijakan privasi'],
['settings_licenses','Licenses','Licencias','Licences','Lizenzen','Licenças','Licenze','Licenties','Лицензии','ライセンス','라이선스','许可证','授權','التراخيص','लाइसेंस','Lisanslar','Licencje','ใบอนุญาต','Lisensi'],
['settings_select_language','Select Language','Seleccionar idioma','Sélectionner la langue','Sprache wählen','Selecionar idioma','Seleziona lingua','Taal selecteren','Выберите язык','言語を選択','언어 선택','选择语言','選擇語言','اختر اللغة','भाषा चुनें','Dil seçin','Wybierz język','เลือกภาษา','Pilih bahasa'],
# === EVENTS HOME ===
['events_home_featured','Featured','Destacados','En vedette','Hervorgehoben','Destaques','In evidenza','Uitgelicht','Рекомендуемые','注目','추천','推荐','推薦','مميز','विशेष','Öne Çıkan','Wyróżnione','แนะนำ','Unggulan'],
['events_home_upcoming','Upcoming Events','Próximos eventos','Événements à venir','Bevorstehende Events','Próximos eventos','Eventi in arrivo','Aankomende evenementen','Предстоящие события','今後のイベント','다가오는 이벤트','即将举行的活动','即將舉行的活動','الأحداث القادمة','आगामी इवेंट्स','Yaklaşan etkinlikler','Nadchodzące wydarzenia','อีเวนท์ที่กำลังจะมาถึง','Acara mendatang'],
['events_home_no_events','No events found','No se encontraron eventos','Aucun événement trouvé','Keine Events gefunden','Nenhum evento encontrado','Nessun evento trovato','Geen evenementen gevonden','События не найдены','イベントが見つかりません','이벤트를 찾을 수 없습니다','未找到活动','未找到活動','لم يتم العثور على أحداث','कोई इवेंट नहीं मिला','Etkinlik bulunamadı','Nie znaleziono wydarzeń','ไม่พบอีเวนท์','Tidak ada acara ditemukan'],
['events_home_clear_filters','Clear Filters','Limpiar filtros','Effacer les filtres','Filter löschen','Limpar filtros','Cancella filtri','Filters wissen','Очистить фильтры','フィルターをクリア','필터 지우기','清除筛选','清除篩選','مسح الفلاتر','फ़िल्टर साफ़ करें','Filtreleri temizle','Wyczyść filtry','ล้างตัวกรอง','Hapus filter'],
# === TICKETS ===
['tickets_my_title','My Tickets','Mis entradas','Mes billets','Meine Tickets','Meus ingressos','I miei biglietti','Mijn tickets','Мои билеты','マイチケット','내 티켓','我的门票','我的票券','تذاكري','मेरे टिकट','Biletlerim','Moje bilety','ตั๋วของฉัน','Tiket saya'],
['tickets_empty_title','No tickets yet','Aún no hay entradas','Pas encore de billets','Noch keine Tickets','Nenhum ingresso ainda','Nessun biglietto ancora','Nog geen tickets','Пока нет билетов','チケットはま`ありません','아직 티켓이 없습니다','还没有门票','還沒有票券','لا توجد تذاكر بعد','अभी कोई टिकट नहीं','Henüz bilet yok','Brak biletów','ยังไม่มีตั๋ว','Belum ada tiket'],
['tickets_empty_subtitle','When you purchase tickets to events they will appear here.','Cuando compres entradas aparecerán aquí.','Vos billets achetés apparaîtront ici.','Gekaufte Tickets erscheinen hier.','Ingressos comprados aparecerão aqui.','I biglietti acquistati appariranno qui.','Gekochte tickets verschijnen hier.','Купленные билеты появятся здесь.','購入したチケットはここに表示されます。','구매한 티켓이 여기에 표시됩니다.','购买的门票将显示在此处。','購買的票券將顯示在此處。','ستظهر التذاكر المشتراة هنا.','खरीदे गए टिकट यहाँ दिखाई देंगे।','Satın alınan biletler burada görünecektir.','Kupione bilety pojawią się tutaj.','ตั๋วที่ซื้อจะแสดงที่นี่','Tiket yang dibeli akan muncul di sini.'],
['tickets_discover','Discover Events','Descubrir eventos','Découvrir des événements','Events entdecken','Descobrir eventos','Scopri eventi','Evenementen ontdekken','Откройте события','イベントを見つける','이벤트 발견','发现活动','發現活動','اكتشف الأحداث','इवेंट्स खोजें','Etkinlikleri keşfet','Odkryj wydarzenia','ค้นพบอีเวนท์','Temukan acara'],
# === PAYMENTS ===
['payments_checkout_title','Checkout','Pagar','Paiement','Kasse','Pagamento','Checkout','Afrekenen','Оформление','購入','결Ԝ','结账','結帳','الدفع','चेकआउट','Ödeme','Płatność','ชำระเงิน','Checkout'],
['payments_buy_tickets','Buy Tickets','Comprar entradas','Acheter des billets','Tickets kaufen','Comprar ingressos','Acquista biglietti','Tickets kopen','Купить билеты','チケットを購入','티켓 구매','购买门票','購買票券','شراء التذاكر','टिकट खरीदें','Bilet satın al','Kup bilety','ซื้อตั๋ว','Beli tiket'],
['payments_sold_out','Sold Out','Agotado','Épuisé','Ausverkauft','Esgotado','Esaurito','Uitverkocht','Распродано','完売','ماقلо','已售罄','已售罄','نفذ','बिक गया','Tükendi','Wyprzedane','ขายหมดแล้ว','Habis terjual'],
['payments_order_summary','Order Summary','Resumen del pedido','Résumé de la commande','Bestellzusammenfassung','Resumo do pedido','Riepilogo ordine','Besteloverzicht','Сводка заказа','注文概要','주문 요약','订单摘要','訂單摘要','ملخص الطلب','ऑर्डर सारांश','Sipariş özeti','Podsumowanie zamówienia','สรุปคำสั่งซื้อ','Ringkasan pesanan'],
['payments_promo_code','Enter promo code','Ingresa código promocional','Entrer un code promo','Promo-Code eingeben','Inserir código promocional','Inserisci codice promo','Voer promotiecode in','Введите промокод','プロモコードを入力','프로모 코드 입력','输入促销代码','輸入促銷代碼','أدخل رمز العرض','प्रोमो कोड दर्ज करें','Promosyon kodu girin','Wpisz kod promocyjny','กรอกรหัสโปรโมชั่น','Masukkan kode promo'],
['payments_success_title','Payment Successful!','¡Pago exitoso!','Paiement réussi!','Zahlung erfolgreich!','Pagamento realizado!','Pagamento riuscito!','Betaling geslaagd!','Оплата успешна!','支払いが完了しました！','결제 성공!','支付成功！','付款成功！','تم الدفع بنجاح!','भुगतान सफल!','Ödeme başarılı!','Płatność udana!','ชำระเงินสำเร็จ!','Pembayaran berhasil!'],
# === PROFILE ===
['profile_edit','Edit Profile','Editar perfil','Modifier le profil','Profil bearbeiten','Editar perfil','Modifica profilo','Profiel bewerken','Редактировать профиль','プロフィール編集','프로필 편집','编辑个人资料','編輯個人資料','تعديل الملف الشخصي','प्रोफ़ाइल संपादित करें','Profili düzenle','Edytuj profil','แก้ไขโปรไฟล์','Edit profil'],
['profile_sign_in_to_access','Sign in to access all features','Inicia sesión para acceder a todas las funciones','Connectez-vous pour accéder à toutes les fonctionnalités','Melden Sie sich an für alle Funktionen','Entre para acessar todos os recursos','Accedi per usare tutte le funzionalità','Log in voor alle functies','Войдите для доступа ко всем функциям','すべての機能にアクセスするにはサインイン','모든 기능에 액세스하려면 로그인','登录以访问所有功能','登入以存取所有功能','سجل الدخول للوصول إلى جميع الميزات','सभी सुविधाओं तक पहुँचने के लिए साइन इन करें','Tüm özelliklere erişmek için giriş yapın','Zaloguj się aby uzyskać dostęp do wszystkich funkcji','เข้าสู่ระบบเพื่อเข้าถึงคุณสมบัติทั้งหมด','Masuk untuk mengakses semua fitur'],
['profile_logout_success','Signed out successfully','Sesión cerrada exitosamente','Déconnecté avec succès','Erfolgreich abgemeldet','Sesião encerrada','Disconnessione riuscita','Succesvol uitgelogd','Выход выполнен','サインアウトしました','로그아웃 되었습니다','已成功退出','已成功登出','تم تسجيل الخروج بنجاح','सफलतापूर्वक साइन आउट हो गया','Başarıyla çıkış yapıldı','Wylogowano pomyślnie','ออกจากระบบสำเร็จ','Berhasil keluar'],
['profile_account','Account','Cuenta','Compte','Konto','Conta','Account','Account','Аккаунт','アカウント','계정','账户','帳戶','الحساب','अकाउंट','Hesap','Konto','บัญชี','Akun'],
['profile_referral','Referral','Referidos','Parrainage','Empfehlung','Indicação','Referral','Verwijzing','Реферал','紹介','추천','推荐','推薦','الإحالة','रेफ़रल','Referans','Polecenie','การแนะนำ','Referral'],
['profile_referral_sub','Share and earn','Comparte y gana','Partagez et gagnez','Teilen und verdienen','Compartilhe e ganhe','Condividi e guadagna','Deel en verdien','Делитесь и зарабатывайте','共有して稼ぐ','공유하고 수익을 얻으세요','分享并赚取','分享並賺取','شارك واربح','साझा करें और कमाएं','Paylaş ve kazan','Udostępnij i zarabiaj','แชร์และรับรายได้','Bagikan dan dapatkan'],
['profile_subscription','Manage Subscription','Administrar suscripción','Gérer l\'abonnement','Abo verwalten','Gerenciar assinatura','Gestisci abbonamento','Abonnement beheren','Управление подпиской','サブスクリプション管理','구독 관리','管理订阅','管理訂閱','إدارة الاشتراк','सदस्यता प्रबंधित करें','Aboneliği yönet','Zarządzaj subskrypcją','จัดการการสมัครสมาชิก','Kelola langganan'],
['profile_transactions','Transactions','Transacciones','Transactions','Transaktionen','Transações','Transazioni','Transacties','Транзакции','取引','거ре','交易','交易','المعاملات','लेनदेन','İşlemler','Transakcje','ธุรกรรม','Transaksi'],
['profile_help','Help Center','Centro de ayuda','Centre d\'aide','Hilfe','Central de ajuda','Centro assistenza','Helpcentrum','Центр помощи','ヘルプセンター','도움말 센터','帮助中心','幫助中心','مركز المساعدة','सहायता केंद्र','Yardım merkezi','Centrum pomocy','ศูนย์ช่วยเหลือ','Pusat bantuan'],
['profile_contact','Contact Us','Contáctanos','Nous contacter','Kontakt','Fale conosco','Contattaci','Neem contact op','Свяжитесь с нами','お問い合わせ','문의하기','联系我们','聯絡我們','اتصل بنا','हमसे संपर्क करें','Bize ulaşın','Skontaktuj się','ติดต่อเรา','Hubungi kami'],
['profile_guest','Guest User','Usuario invitado','Utilisateur invité','Gastbenutzer','Usuário convidado','Utente ospite','Gastgebruiker','Гость','ゲスト','게스트','访客','訪客','ضيف','अतिथि','Misafir','Gość','ผู้เยี่ยมชม','Tamu'],
# === WALLET ===
['wallet_title','Wallet','Billetera','Portefeuille','Wallet','Carteira','Portafoglio','Portemonnee','Кошелек','ウォレット','지갑','钱包','錢包','المحفظة','वॉलेट','Cüzdan','Portfel','กระเป๋าเงิน','Dompet'],
['wallet_send_ada','Send ADA','Enviar ADA','Envoyer ADA','ADA senden','Enviar ADA','Invia ADA','ADA verzenden','Отправить ADA','ADAを送信','ADA 보내기','发送 ADA','發送 ADA','إرسال ADA','ADA भेजें','ADA gönder','Wyślij ADA','ส่ง ADA','Kirim ADA'],
['wallet_receive_ada','Receive ADA','Recibir ADA','Recevoir ADA','ADA empfangen','Receber ADA','Ricevi ADA','ADA ontvangen','Получить ADA','ADAを受信','ADA 받기','接收 ADA','接收 ADA','استلام ADA','ADA प्राप्त करें','ADA al','Odbierz ADA','รับ ADA','Terima ADA'],
['wallet_link_bank','Link Bank Account','Vincular cuenta bancaria','Lier un compte bancaire','Bankkonto verknüpfen','Vincular conta bancária','Collega conto bancario','Bankrekening koppelen','Привязать банковский счет','銀行口座を連携','은행 계좌 연결','关联银行账户','關聯銀行帳戶','ربط الحساب المصرفي','बैंक खाता लिंक करें','Banka hesabı bağla','Połącz konto bankowe','เชื่อมต่อบัญชีธนาคาร','Hubungkan rekening bank'],
# === SUBSCRIPTION ===
['subscription_title','Subscription','Suscripción','Abonnement','Abonnement','Assinatura','Abbonamento','Abonnement','Подписка','サブスクリプション','구독','订阅','訂閱','الاشتراк','सदस्यता','Abonelik','Subskrypcja','การสมัครสมาชิก','Langganan'],
['subscription_available_plans','Available Plans','Planes disponibles','Plans disponibles','Verfügbare Pläne','Planos disponíveis','Piani disponibili','Beschikbare plannen','Доступные планы','利用可能なプラン','이용 가능한 플랜','可用计划','可用方案','الخطط المتاحة','उपलब्ध योजनाएं','Mevcut planlar','Dostępne plany','แผนที่มีให้เลือก','Paket tersedia'],
['subscription_cancel','Cancel Subscription?','\¿Cancelar suscripci\ón?','Annuler l\'abonnement?','Abo k\ündigen?','Cancelar assinatura?','Annullare abbonamento?','Abonnement opzeggen?','Отменить подписку?','サブスクリプションをキャンセルしますか？','구독을 취소하시겠습니까?','取消订阅？','取消訂閱？','إلغاء الاشتراк؟','सदस्यता रद्द करें?','Aboneliği iptal et?','Anulować subskrypcję?','ยกเลิกการสมัคร?','Batalkan langganan?'],
['subscription_cancel_plan','Cancel Plan','Cancelar plan','Annuler le plan','Plan kündigen','Cancelar plano','Annulla piano','Plan opzeggen','Отменить план','プランをキャンセル','플랜 취소','取消计划','取消方案','إلغاء الخطة','योजना रद्द करें','Planı iptal et','Anuluj plan','ยกเลิกแผน','Batalkan paket'],
['subscription_keep_plan','Keep Plan','Mantener plan','Garder le plan','Plan behalten','Manter plano','Mantieni piano','Plan behouden','Оставить план','プランを維持','플랜 유지','保留计划','保留方案','إبقاء الخطة','योजना रखें','Planı koru','Zachowaj plan','คงแผน','Pertahankan paket'],
['subscription_resumed','Subscription resumed','Suscripción reanudada','Abonnement repris','Abo fortgesetzt','Assinatura retomada','Abbonamento ripreso','Abonnement hervat','Подписка возобновлена','サブスクリプションが再開されました','구독이 재개되었습니다','订阅已恢复','訂閱已恢復','تم استئناف الاشتراк','सदस्यता फिर से शुरू हुई','Abonelik devam ettirildi','Subskrypcja wznowiona','การสมัครสมาชิกกลับมาทำงานต่อ','Langganan dilanjutkan'],
['subscription_referral_benefit','Referral reward: upgrade to Pro and get 50% off for 6 months!','Recompensa de referido: mejora a Pro y obtiene 50% de descuento por 6 meses!','Récompense de parrainage: passez au Pro et obtenez 50% de réduction pendant 6 mois!','Empfehlungsbonus: Upgraden Sie auf Pro und erhalten Sie 50% Rabatt für 6 Monate!','Recompensa de indicação: atualize para Pro e ganhe 50% de desconto por 6 meses!','Ricompensa referral: passa a Pro e ottieni il 50% di sconto per 6 mesi!','Verwijzingsbeloning: upgrade naar Pro en krijg 50% korting voor 6 maanden!','Бонус за реферал: обновитесь до Pro и получите 50% скидку на 6 месяцев!','紹介特典: Proにアップグレードで6ヶ月間50%オフ!','추천 보상: Pro로 업그레이드하고 6개월간 50% 할인!','推荐奖励：升级到Pro可享受6个月半价！','推薦獎勵：升級到Pro可享受6個月半價！','مكافأة الإحالة: قم بالترقية إلى Pro واحصل على خصم 50٪ لمدة 6 أشهر!','रेफ़रल पुरस्कार: Pro में अपग्रेड करें और 6 महीने के लिए 50% की छूट पाएं!','Referans ödülü: Pro\'ya yükseltin ve 6 ay boyunca %50 indirim kazanın!','Nagroda za polecenie: przejdź na Pro i uzyskaj 50% zniżki na 6 miesięcy!','รางวัลการแนะนำ: อัปเกรดเป็น Pro และรับส่วนลด 50% นาน 6 เดือน!','Hadiah referral: upgrade ke Pro dan dapatkan diskon 50% selama 6 bulan!'],
# === NOTIFICATIONS ===
['notifications_title','Notifications','Notificaciones','Notifications','Benachrichtigungen','Notificações','Notifiche','Meldingen','Уведомления','通知','알림','通知','通知','الإشعارات','सूचनाएं','Bildirimler','Powiadomienia','การแจ้งเตือน','Notifikasi'],
['notifications_empty','No notifications','Sin notificaciones','Aucune notification','Keine Benachrichtigungen','Sem notificações','Nessuna notifica','Geen meldingen','Нет уведомлений','通知はありません','알림이 없습니다','没有通知','沒有通知','لا توجد إشعارات','कोई सूचना नहीं','Bildirim yok','Brak powiadomień','ไม่มีการแจ้งเตือน','Tidak ada notifikasi'],
['notifications_mark_all','Mark all as read','Marcar todo como leído','Tout marquer comme lu','Alle als gelesen markieren','Marcar tudo como lido','Segna tutto come letto','Alles als gelezen markeren','Отметить все как прочитанные','すべて既読にする','모두 읽음으로 표시','全部标记为已读','全部標記為已讀','تعليم الكل كمقروء','सभी को पढ़ा हुआ चिह्नित करें','Tümünü okundu olarak işaretle','Oznacz wszystkie jako przeczytane','ทำเครื่องหมายว่าอ่านแล้วทั้งหมด','Tandai semua sebagai dibaca'],
# === ERROR MESSAGES ===
['error_network','No internet connection','Sin conexión a internet','Pas de connexion internet','Keine Internetverbindung','Sem conexão com a internet','Nessuna connessione internet','Geen internetverbinding','Нет интернет-соединения','インターネット接続なし','인터넷 연결 없음','无网络连接','無網路連接','لا يوجد اتصال بالإنترنت','इंटरनेट कनेक्शन नहीं','\İnternet ba\ğlant\ıs\ı yok','Brak połączenia z internetem','ไม่มีการเชื่อมต่ออินเทอร์เน็ต','Tidak ada koneksi internet'],
['error_something_wrong','Something went wrong. Please try again.','Algo salió mal. Por favor intenta de nuevo.','Une erreur est survenue. Veuillez réessayer.','Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.','Algo deu errado. Tente novamente.','Qualcosa è andato storto. Riprova.','Er is iets misgegaan. Probeer het opnieuw.','Что-то пошло не так. Попробуйте еще раз.','問題が発生しました。もう一度お試しください。','문제가 발생했습니다. 다시 시도해주세요.','出错了。请重试。','出錯了。請重試。','حدث خطأ. يرجى المحاولة مرة أخرى.','कुछ गलत हो गया। कृपया पुनः प्रयास करें।','Bir şeyler ters gitti. Lütfen tekrar deneyin.','Coś poszło nie tak. Spróbuj ponownie.','เกิดข้อผิดพลาด กรุณาลองอีกครั้ง','Terjadi kesalahan. Silakan coba lagi.'],
['error_try_again','Try Again','Intentar de nuevo','Réessayer','Erneut versuchen','Tentar novamente','Riprova','Probeer opnieuw','Попробовать снова','もう一度','다시 시도','重试','重試','حاول مرة أخرى','फिर से प्रयास करें','Tekrar dene','Spróbuj ponownie','ลองอีกครั้ง','Coba lagi'],
# === REFERRAL ===
['referral_title','Referral','Referidos','Parrainage','Empfehlung','Indicação','Referral','Verwijzing','Реферал','紹介','추천','推荐','推薦','الإحالة','रेफ़रल','Referans','Polecenie','การแนะนำ','Referral'],
['referral_code_label','Your Referral Code','Tu código de referido','Votre code de parrainage','Ihr Empfehlungscode','Seu código de indicação','Il tuo codice referral','Jouw verwijzingscode','Ваш реферальный код','あなたの紹介コード','내 추천 코드','您的推荐码','您的推薦碼','رمز الإحالة الخاص بк','आपका रेफ़रल कोड','Referans kodunuz','Twój kod polecenia','รหัสแนะนำของคุณ','Kode referral Anda'],
['referral_code_copied','Referral code copied!','¡Código de referido copiado!','Code de parrainage copié!','Empfehlungscode kopiert!','Código de indicação copiado!','Codice referral copiato!','Verwijzingscode gekopieerd!','Реферальный код скопирован!','紹介コードをコピーしました!','추천 코드가 복사되었습니다!','推荐码已复制！','推薦碼已複製！','تم نسخ رمز الإحالة!','रेफ़रल कोड कॉपी हो गया!','Referans kodu kopyalandı!','Kod polecenia skopiowany!','คัดลอกรหัสแนะนำแล้ว!','Kode referral disalin!'],
['referral_share_link','Share Link','Compartir enlace','Partager le lien','Link teilen','Compartilhar link','Condividi link','Link delen','Поделиться ссылкой','リンクを共有','링크 공유','分享链接','分享連結','مشاركة الرابط','लिंक साझा करें','Linki paylaş','Udostępnij link','แชร์ลิงก์','Bagikan tautan'],
['referral_stats','Your Stats','Tus estadísticas','Vos statistiques','Ihre Statistiken','Suas estatísticas','Le tue statistiche','Jouw statistieken','Ваша статистика','あなたの統計','내 통계','您的统计','您的統計','إحصائياتк','आपके आँकड़े','İstatistikleriniz','Twoje statystyki','สถิติของคุณ','Statistik Anda'],
['referral_referrals','Referrals','Referidos','Parrainages','Empfehlungen','Indicações','Referral','Verwijzingen','Рефералы','紹介','추천','推荐','推薦','إحالات','रेफ़रल','Referanslar','Polecenia','การแนะนำ','Referral'],
['referral_earned','Earned','Ganado','Gagné','Verdient','Ganho','Guadagnato','Verdiend','Заработано','獲得','수익','赚取','賺取','الأرباح','कमाई','Kazanılan','Zarobione','รายได้','Diperoleh'],
['referral_pending','Pending','Pendiente','En attente','Ausstehend','Pendente','In sospeso','In afwachting','В ожидании','保留中','대기 중','待处理','待處理','قيد الانتظار','लंबित','Beklemede','Oczekujące','รอดำเนินการ','Tertunda'],
['referral_how_it_works','How It Works','Cómo funciona','Comment ça marche','So funktioniert es','Como funciona','Come funziona','Hoe het werkt','Как это работает','仕組み','이용 방법','如何运作','如何運作','كيف يعمل','कैसे काम करता है','Nasıl çalışır','Jak to działa','วิธีการทำงาน','Cara kerja'],
['referral_withdraw','Withdraw Earnings','Retirar ganancias','Retirer les gains','Auszahlung','Sacar ganhos','Ritira guadagni','Inkomsten opnemen','Вывести заработок','収益を引き出す','수익 인출','提取收益','提取收益','سحب الأرباح','कमाई निकालें','Kazancı çek','Wypłać zarobki','ถอนรายได้','Tarik penghasilan'],
['referral_channel_performance','Channel Performance','Rendimiento del canal','Performance des canaux','Kanal-Performance','Desempenho do canal','Performance canale','Kanaalprestaties','Эффективность каналов','チャネルパフォーマンス','채널 성과','渠道表现','渠道表現','أداء القناة','चैनल प्रदर्शन','Kanal performansı','Wydajność kanałów','ประสิทธิภาพช่องทาง','Kinerja saluran'],
['referral_clicks','Clicks','Clics','Clics','Klicks','Cliques','Clic','Klikken','Клики','クリック','클릭','点击','點擊','نقرات','क्लिक','Tıklamalar','Kliknięcia','คลิก','Klik'],
['referral_signups','Signups','Registros','Inscriptions','Registrierungen','Cadastros','Iscrizioni','Registraties','Регистрации','登録','가입','注册','註冊','تسجيلات','साइनअप','Kayıtlar','Rejestracje','สมัคร','Pendaftaran'],
['referral_sales','Sales','Ventas','Ventes','Verkäufe','Vendas','Vendite','Verkopen','Продажи','売上','판매','销售','銷售','مبيعات','बिक्री','Satışlar','Sprzedaż','ยอดขาย','Penjualan'],
['referral_dashboard_title','Referral Dashboard','Panel de referidos','Tableau de parrainage','Empfehlungs-Dashboard','Painel de indicações','Dashboard referral','Verwijzingsdashboard','Панель рефералов','紹介ダッシュボード','추천 대시보드','推荐仪表板','推薦儀表板','لوحة الإحالات','रेफ़रल डैशबोर्ड','Referans panosu','Panel poleceń','แดชบอร์ดการแนะนำ','Dasbor referral'],
['referral_top_referrers','Top Referrers','Mejores referidores','Meilleurs parrains','Top Empfehler','Melhores indicadores','Top referrer','Top verwijzers','Лучшие рефереры','トップ紹介者','상위 추천인','最佳推荐者','最佳推薦者','أفضل المحيلين','शीर्ष रेफ़रर','En iyi referanslar','Najlepsi polecający','ผู้แนะนำยอดนิยม','Perujuk teratas'],
['referral_funnel','Funnel Breakdown','Desglose del embudo','Détail de l\'entonnoir','Trichter-Analyse','Detalhes do funil','Analisi funnel','Trechteranalyse','Анализ воронки','ファネル分析','퍼널 분석','漏斗分析','漏斗分析','تحليل القمع','फनल विश्लेषण','Huni analizi','Analiza ścieżki','วิเคราะห์ช่องทาง','Analisis corong'],
]
# fmt: on

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'localization.csv')
with open(out_path, 'w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['Id'] + LANGS)
    for row in STRINGS:
        # Pad row to match header length (19 columns)
        while len(row) < len(LANGS) + 1:
            row.append('')
        writer.writerow(row)

print(f'Generated {len(STRINGS)} strings to {out_path}')
